### ISSUE TITLE
SQLAlchemy error - MySQL

### ISSUE THREAD

**Issue by wolfnacht44** [Donkie/Spoolman#86]
Hope I can get some input here and didn't mess anything up upon install.
I'm utilizing the install with Portainer, using the template as a guide.
Spoolman connects to the mysql server DB without any problems (networked locally and remotely)

However when trying to add any entry from any tab webUI throws a 500 exception, and container log reports [THIS](https://pastebin.com/sx2B3Qu4) <- Pastebin 

manually adding an entry shows just fine, and is fully editable.

using SQL Lite DB works fine, and I spun up a VM and tested on hardware with docker-compose and encountered the same issue. 
again SQL Lite works with no issue in both alternative scenarios.

i have not yet with Maria, Postgres, etc. as mysql is what I have deployed with redundancy

any assistance is deeply appreciated!

also, ability to export/import, as a *.csv as  a feature would be excellent

**Comment by wolfnacht44** [comment]
For what it's worth, I did spin up a dirty Maria, and postgres dbs, db entry works, mysql (mysql  Ver 8.0.34) does not.
I would really prefer not to have to run a 3rd independent db just spoolman. mysql is currently deployed across my network with remote redundancy and load balance

**Comment by Donkie** [comment]
Your pastebin is private so I cannot see it

**Comment by wolfnacht44** [comment]
@Donkie 
[try this one](https://pastes.io/6vrliawp5f)

didnt realize pastebin "detected offensive language" would only go private.... 
i hate using that site anymore but i wont flood a post with the error output

**Comment by Donkie** [comment]
Strange. Could you give me the exact version of MySQL you're using, what server it's hosted on and if you have any plugins or something installed?

**Comment by wolfnacht44** [comment]
> mysql Ver 8.0.34-0ubuntu0.23.04.1 for Linux on x86_64
     is on my local network





[Local SHOW PLUGINS;](https://pastes.io/gcjqchdgbd)
no real use for plugins in home( I try to keep it as simple as possible), at the office is another story. 

Just spun up another machine, with a fresh instance of mysql in a LXC with new hardware that was delivered this morning

> mysql  Ver 8.0.34 for Linux on x86_64 (MySQL Community Server - GPL)
new machine in LXC - ubuntu23.04 is the template

[SHOW PLUGINS;](https://pastes.io/luk19sx6b9)

[log from fresh spoolman instnace with new creds](https://pastes.io/lnuadpagdj)

I'm in the process of some major network/hardware upgrades today, so until the everything settles down, my reponses may be delayed.
I really appreciate, the swift follow-ups

**Comment by Donkie** [comment]
I'm having a hard time reproducing this issue, but I have a suspicion on what it is. I've pushed some updates to the `edge` tag, so see if that solves your problem. `ghcr.io/donkie/spoolman:edge`

**Comment by wolfnacht44** [comment]
Hey Donkie,

    Apologize for the delay, had some unfortunate turn of events in the last week. However Spoolman still throwing an error with MySQL on creating an entry. Editing an entry is still fine. This is also with a clean, fresh install of MySQL from ubuntu repo. I figured I'd give it the best possible chance. Still no dice. I've spun up a MariaDB in the meantime to get me by. 

Log linked below
[edge-branch-log](https://pastes.io/gnafiqxvf4)

I'm not sure how to reporduce the error outright. Especially if other DBs are working fine. 
MySQL is run in an Ubuntu LXC container in ProxMox8
Portainer is run in the same manner, and even raw docker instance was done this way as well.
Maria was deployed as an LXC and Postgres was Deployed in portainer when i tested those methods.
Browser in use is Firefox. but i also encounter the error in Chrome on mobile. 

trying to be as helpful as I can. I love the project.

**Comment by Donkie** [comment]
See if the latest release fixes this issue for you

**Comment by wolfnacht44** [comment]
Will do as soon as I can and report back.

**Comment by Donkie** [comment]
Closing for now, re-open if issue appears again
